src/trayicon.rs

feat: Add checkbox to startup menu item

---

src/switcher.rs

If the interval between two hotkey pressing is less than 3 seconds, switch windows cyclically,
otherwise switch to the previous window.

feat: hotkey interval time affects behavior

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
src/app.rs
src/config.rs
src/startup.rs
src/switcher.rs
src/trayicon.rs

Hotkey full-release switch to the window that was focused on last full-release.
Hotkey half-release cycle windows
close #18

feat: deal hotkey full/half release different

---

src/app.rs
src/config.rs
src/main.rs
src/switcher.rs
windows-switcher.ini

feat: support blacklist

---

README.md
src/app.rs
src/config.rs
src/main.rs
src/switcher.rs
windows-switcher.ini

BREAKING CHANGE: configuration structure changed

feat: adjust the configuration file

---

src/app.rs
src/config.rs
src/keyboard.rs
src/utils.rs

if you set switch app hotkey to ``` `alt+` ```, both left/right alt plus ``` ` ``` will trigger the switching.

feat:  both left/right modifier key works

---

src/app.rs

When you press alt+tab, you can press ` to switch windows of current selected application

feat: support switching window while switching application

---

README.md
src/app.rs
src/config.rs
src/utils/window.rs
window-switcher.ini

```ini
[switch-windows]
ignore_minimal = no
[switch-apps]
ignore_minimal = no
```

feat: controls whether to skip the minimum windows

---

src/app.rs

fix: switch to all-mininal-windows app chooses wrong window

---

src/app.rs

fix: select last app when press switch-apps hotkey with shift

---

src/startup.rs

fix: fatal error on get reg value

---

src/utils/window.rs

fix: hide small windows

---

src/app.rs

fix: crash when alt+tab but no window is opened

---

src/config.rs
src/foreground.rs

fix: blacklist not work

---

src/config.rs

feat: support more keycodes such as vk_oem_102

---

README.md

This probably slipped in unintentionally.

chore: fix broken link in readme

---

src/app.rs
src/keyboard.rs

While `alt+tab` swiching apps, press `esc` would only exit the switcher, and not make the switch to the app.
close #115

feat: `esc` exit the switch app ui

---

src/utils/app_icon.rs

fix: unexpected display some app icons tiny

---

src/painter.rs

feat: light theme follows system settings

---

src/utils/window.rs
tools/inspect-windows/src/main.rs

fix: switch app does not list apps with borderless windows
